services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internship-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: npm run start