services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
      JWT_SECRET: ${JWT_SECRET}
    command: npm run start
    networks:
      - bus-network

networks:
  bus-network:
    external: true