name: Trigger Jenkins SonarQube Job

on:
  push:
    branches:
      - suphasan

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Get Jenkins Crumb
        id: crumb
        run: |
          CRUMB=$(curl -s 'http://94.237.73.171:8080/crumbIssuer/api/json' | jq -r '.crumb')
          echo "crumb=$CRUMB" >> $GITHUB_OUTPUT

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://94.237.73.171:8080/job/Bussing-API/build?token=my_token" \
            -H "Jenkins-Crumb: ${{ steps.crumb.outputs.crumb }}"